name = "couch-url-rewrite-proxy"
description = "a proxy that rewrites URLs on their way out of couch, making registry migrations easier"
start = "./bin/couch-url-rewrite-proxy.js start"

[environment]
	FRONT_DOOR_HOST = "{{front_door_url}}"
	PORT = "{{port}}"
	UPSTREAM_URL = "{{upstream_url}}"
