sudo: required
services:
- docker
language: node_js
node_js:
- '6'
- '8'
git:
  depth: false
cache:
  directories:
  - ".git"
before_install:
- openssl aes-256-cbc -K $encrypted_61c36e2f4bb0_key -iv $encrypted_61c36e2f4bb0_iv
  -in key.json.enc -out key.json -d
- npm i -g npm@latest
- npm i @npm-wharf/shipwright -g
- printf "@npm:registry=https://enterprise.npmjs.com" >> ~/.npmrc
- cat key.json | docker login -u=_json_key --password-stdin https://gcr.io/
install:
- npm ci
script:
- npm test
- shipwright build image --registry=gcr.io/npm-image-registry-prod --repo=npmjs --name=couch-url-rewrite-proxy --tags=lm,v_s,v,miv,ma,b,b_v_c_s --build-branches=master,qa,dev,deploy-staging,deploy-npme --cache-from-latest --flatten
after_success:
- npm run coverage
